### ISSUE TITLE
Reducing image blur on Chrome and Safari

### ISSUE THREAD

**Issue by markaharper** [heavybeard/advanced-zoom#6]
I added the following to the end of the css file

.zoom-overlay-open, .zoom-overlay-transitioning { cursor: default; image-rendering: -webkit-optimize-contrast; -ms-interpolation-mode: nearest-neighbor; }

This dramatically reduced the blurring in both Chrome and Safari without effecting Firefox.

As per a suggestion: https://github.com/fat/zoom.js/issues/54

**Comment by heavybeard** [comment]
As you suggest, I'll add the css lines. Thank you again
