### ISSUE TITLE
README.md: needs to read 'data-zoom-original'

### ISSUE THREAD

**Issue by markaharper** [heavybeard/advanced-zoom#7]
On your README.md page under 'Why':

<img src="asset/img/city.jpg" data-zoom="zoom" data-original="asset/img/city.jpg">

But the source code on your examples uses "data-zoom-original".

I switched to "data-zoom-original" and it worked.

Thank you so much for advanced-zoom, it has saved the day after zoom.js was blurring the images too much.

**Comment by heavybeard** [comment]
Hi @markaharper ,
thanks for your help. I'll fix it now!
